ROOT_DIR := $(realpath ../../..)
include $(ROOT_DIR)/config.mk

PROJECT := my_sched_test

SRC_DIR := $(VORTEX_HOME)/tests/kernel/$(PROJECT)

SRCS := $(SRC_DIR)/my_sched_test.c

CFLAGS += -I/home/houdong/vortex/sw/runtime/include

include ../common.mk